server/config/routes.rb
Marketplace::Application.routes.draw do
  root :to => "apps#index"
  
  resources :apps do
    collection do
      post 'exists', 'ids'
    end
    resources :visuals do
      collection do
        post 'exists'
      end
    end
  end
  
  resources :app_targets do
    collection do
      post 'exists'
    end
  end
  
  resources :app_permissions do
    collection do
      post 'update_permissions'
    end
  end
  
  resources :comments do 
    collection do
      post 'exists'
    end
  end
  
  resources :permissions
  
  
  

end

server/app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :packageName %><br />
    <%= f.text_field :packageName %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :appId %><br />
    <%= f.text_field :appId %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :recentChanges %><br />
    <%= f.text_area :recentChanges %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :versionCode %><br />
    <%= f.text_field :versionCode %>
  </div>
  <div class="field">
    <%= f.label :appType %><br />
    <%= f.text_field :appType %>
  </div>
  <div class="field">
    <%= f.label :promoText %><br />
    <%= f.text_area :promoText %>
  </div>
  <div class="field">
    <%= f.label :promoVideo %><br />
    <%= f.text_field :promoVideo %>
  </div>
  <div class="field">
    <%= f.label :screenshotCount %><br />
    <%= f.text_field :screenshotCount %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :priceCurrency %><br />
    <%= f.text_field :priceCurrency %>
  </div>
  <div class="field">
    <%= f.label :installSize %><br />
    <%= f.text_field :installSize %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

server/app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Creator</th>
    <th>Category</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.title %></td>
    <td><%= app.creator %></td>
    <td><%= app.category %></td>
    <td><%= app.price %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

server/app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

server/app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Creator:</b>
  <%= @app.creator %>
</p>

<p>
  <b>Packagename:</b>
  <%= @app.packageName %>
</p>

<p>
  <b>Title:</b>
  <%= @app.title %>
</p>

<p>
  <b>Description:</b>
  <%= @app.description %>
</p>

<p>
  <b>Appid:</b>
  <%= @app.appId %>
</p>

<p>
  <b>Category:</b>
  <%= @app.category %>
</p>

<p>
  <b>Recentchanges:</b>
  <%= @app.recentChanges %>
</p>

<p>
  <b>Email:</b>
  <%= @app.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @app.phone %>
</p>

<p>
  <b>Website:</b>
  <%= @app.website %>
</p>

<p>
  <b>Version:</b>
  <%= @app.version %>
</p>

<p>
  <b>Versioncode:</b>
  <%= @app.versionCode %>
</p>

<p>
  <b>Apptype:</b>
  <%= @app.appType %>
</p>

<p>
  <b>Promotext:</b>
  <%= @app.promoText %>
</p>

<p>
  <b>Promovideo:</b>
  <%= @app.promoVideo %>
</p>

<p>
  <b>Screenshotcount:</b>
  <%= @app.screenshotCount %>
</p>

<p>
  <b>Price:</b>
  <%= @app.price %>
</p>

<p>
  <b>Pricecurrency:</b>
  <%= @app.priceCurrency %>
</p>

<p>
  <b>Installsize:</b>
  <%= @app.installSize %>
</p>

<p>
  <b>Rating:</b>
  <%= @app.rating.rating %>
</p>

<p>
  <b>Rating Count:</b>
  <%= @app.rating.ratingCount %>
</p>

<p>
  <b>Download Count:</b>
  <%= @app.rating.downloadCount %>
</p>

<p>
  <b>Download Count (text):</b>
  <%= @app.rating.downloadCountText %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>